### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by sanjayen** [Magisk-Modules-Repo/crokrammgmtfix#3]
Crok - I do not see this module in the Magisk Manager downloads list. How can I install the module using this repo? I am using MIUI EU ROM for Mi5.

Thank you. Keep up the good work.

**Comment by crok** [comment]
Hi, [a user reported a couple of hours ago](https://github.com/Magisk-Modules-Repo/crokrammgmtfix/issues/2) a typo and I corrected it in minutes, then the user reported that it is working fine - thus I assume the module is listed in Magisk Manager. How did you try to look for the module? If it is not listed then you can download the zip manually, copy it to your phone and install it manually from Magisk Manager. To download the zip go to [this release page](https://github.com/Magisk-Modules-Repo/crokrammgmtfix/releases/tag/v0.0.1) here and download the version [v0.0.1](https://github.com/Magisk-Modules-Repo/crokrammgmtfix/archive/v0.0.1.zip).

**Comment by crok** [comment]
@sanjayen: any update? Did it work? Is it listed?

**Comment by sanjayen** [comment]
@crok apologies for the delay but yes I did manage to install the module using Magisk inbuilt download. The module was not listed earlier in Magisk but is displayed correctly and installs perfectly. Thank you for creating this module.
