### ISSUE TITLE
Module not Working with Magisk v16.4

### ISSUE THREAD

**Issue by Schroedinger00** [Magisk-Modules-Repo/crokrammgmtfix#4]
Hello, and thank you for the Great module!

However i cant install it anymore on magisk 16.4, since it cannot find "/data/magisk/", and it says that Magisk isn't setup properly, which it is. 

I hope you can fix or update your module to v16.4 :) (they removed that old folder)

greetings :)

**Comment by crok** [comment]
Hi,

I don't know about any template upgrade lately - nor I'm using "/data/magisk/" directly anywhere in my module. 16.4 version is a beta version - so are you sure it is not problem of Magisk itself? Is /data is mounted in your TWRP (or basically in your recovery)?

It works for others.

But if you think this is a module issue then can you point me where it is documented that /data/magisk/ has been removed or moved?

**Comment by Schroedinger00** [comment]
everything works fine, /data too. 

Any other Modules work fine, but yours shows me the error (tried multiple Installs etc)
very weird.

i found this (his changelogs): https://forum.xda-developers.com/showpost.php?p=68966755&postcount=2

check the Spoiler below it with v16.3 :) -> removed symlinks for older versions (backwards compatibility)

I hope this helps you :)

**Comment by crok** [comment]
It does not help, it has no info on /data/magisk/

Provide some logs and/or evidence.

**Comment by Schroedinger00** [comment]
I have found this: https://forum.xda-developers.com/apps/magisk/official-magisk-v7-universal-systemless-t3473445/post76042873#post76042873

He changed the Paths to be more Secure but he does not Write it in XDA

You have to check his changes etc. on GitHub (maybe his new Template)

I am not a Developer, I can't help you anymore than this :/


Also log from Magisk: 

[install_log_20180514_130834.log](https://github.com/Magisk-Modules-Repo/crokrammgmtfix/files/2001705/install_log_20180514_130834.log)

**Comment by crok** [comment]
Okay, check release 0.0.2 please.

**Comment by Schroedinger00** [comment]
Okay will check and report back :)

**Comment by Schroedinger00** [comment]
Installed without Problems and works perfectly :)

thank you very much for your work! :)
very nice module :)

**Comment by crok** [comment]
I'm glad it works for you! Thank you for reporting the incompatibility!
