### ISSUE TITLE
Avoid sleeping in service.sh

### ISSUE THREAD

**Issue by Ristovski** [Magisk-Modules-Repo/crokrammgmtfix#6]
Opening here since can't open issues at https://github.com/crok/crokrammgmtfix

The current `service.sh` [sleeps for 30 seconds ](https://github.com/Magisk-Modules-Repo/crokrammgmtfix/blob/master/common/service.sh#L12) which blocks other modules that come after `crokrammgmtfix` from starting their `service.sh` by the same amount.

More info at https://github.com/kitsunyan/foxy-boot/issues/3#issuecomment-484682911

**Comment by crok** [comment]
Hello,
removed the waiting, although it worked perfectly in older Magisk releases afaik.
